import { promises as fs } from 'fs';
import { dirname, join, resolve } from 'path';

/**
 * Where the (already encrypted) bytes live. Stores never see plaintext and know nothing about
 * keys or tenants; `StorageService` does the encryption and picks the store.
 */
export interface BlobStore {
  put(key: string, data: Buffer): Promise<void>;
  /** Must throw `StoredObjectMissingError` (not an adapter-specific error) when the object is absent. */
  get(key: string): Promise<Buffer>;
  /** Must succeed when the object is already absent, so a retried erasure can finish. */
  delete(key: string): Promise<void>;
}

/** The object is gone (for example erased by retention). Adapters must throw this, not their own error. */
export class StoredObjectMissingError extends Error {
  constructor() {
    super('Stored object is missing');
    this.name = 'StoredObjectMissingError';
  }
}

/** Keys are generated by the service (`tenant/session/uuid`); anything else is a bug or an attack. */
export function assertSafeKey(key: string): void {
  if (!/^[A-Za-z0-9][A-Za-z0-9._\/-]{0,300}$/.test(key) || key.split('/').some((p) => p === '' || p === '.' || p === '..')) {
    throw new Error('Invalid storage key');
  }
}

/** Development store: files on local disk. Single host only. */
export class LocalBlobStore implements BlobStore {
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  private path(key: string): string {
    const full = resolve(join(this.root, key));
    if (!full.startsWith(this.root + '/')) throw new Error('Invalid storage key');
    return full;
  }

  async put(key: string, data: Buffer): Promise<void> {
    const file = this.path(key);
    await fs.mkdir(dirname(file), { recursive: true });
    await fs.writeFile(file, data, { mode: 0o600 });
  }

  async get(key: string): Promise<Buffer> {
    try {
      return await fs.readFile(this.path(key));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') throw new StoredObjectMissingError();
      throw err;
    }
  }

  async delete(key: string): Promise<void> {
    await fs.rm(this.path(key), { force: true });
  }
}
